version: "3.5"

services:
  pg_db:
    image: postgres:14.10-alpine3.19
    container_name: orderservice_db
    restart: always
    environment:
      - POSTGRES_DB=orderservice
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=353062
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data postgres

volumes:
  db: