version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=microservices_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=353062
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5420:5432"

volumes:
  db: